[package]
name = "sp1-test"
version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
sp1-test-macro.workspace = true
rand.workspace = true
sha2-v0-9-8.workspace = true
parking_lot = "0.12.3"
