[workspace]
[package]
name = "RustCrypto-bigint-test"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "bigint_test"
path = "bin/base.rs"

[dependencies]
sp1-zkvm = { path = "../../../crates/zkvm/entrypoint" }
num-bigint = "0.4.0"

[patch.crates-io]
crypto-bigint = { git = "https://github.com/sp1-patches/RustCrypto-bigint", tag = "crypto_bigint-v0.5.5-patch-v1" }
