[workspace]
[package]
name = "bls12_381_test_program"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "bls12_381_test_inverese"
path = "bin/test_inverse.rs"

[[bin]]
name = "bls12_381_test_sqrt"
path = "bin/test_sqrt.rs"

[dependencies]
sp1-lib = { path = "../../../crates/zkvm/lib" }
sp1-zkvm = { path = "../../../crates/zkvm/entrypoint" }
bls12_381 = { git = "https://github.com/sp1-patches/bls12_381", branch = "n/prep-4.0.0" }

[patch.crates-io]
sp1-lib = { path = "../../../crates/zkvm/lib" }
