[package]
name = "bn"
version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
sp1-zkvm = { workspace = true }
sp1-sdk = { workspace = true }
rand = { workspace = true }
sp1-test = { workspace = true }

[features]
cpu = []
gpu = ["sp1-sdk/cuda"]

[build-dependencies]
sp1-build = { workspace = true }
