[workspace]
[package]
name = "curve25519-dalek-ng"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "curve25519_ng_decompress"
path = "bin/decompress.rs"

[dependencies]
sp1-zkvm = { path = "../../../crates/zkvm/entrypoint" }
ed25519-dalek = { version = "2.1.0", features = ["alloc", "serde"] }
curve25519-dalek = { version = "4.1.3", default-features = false, features = ["alloc", "serde"] }

[patch.crates-io]
# patches are not transitvely applied to patches lmao
curve25519-dalek = { git = "https://github.com/sp1-patches/curve25519-dalek", branch = "n/prep-4.0.0" }
# Temporarily pinning to a specific version of ed25519-dalek to avoid a build failure
sp1-lib = { path = "../../../crates/zkvm/lib" }
